### ISSUE TITLE
README make scope error

### ISSUE THREAD

**Issue by abcoathup** [Cyfrin/forge-template#2]
README Audit scope details section `make scope` gives error
https://github.com/Cyfrin/forge-template?tab=readme-ov-file#audit-scope-details

```
$ make scope
tree ./src/ | sed 's/└/#/g; s/──/--/g; s/├/#/g; s/│ /|/g; s/│/|/g'
/bin/sh: 1: tree: not found
```

**Comment by PatrickAlphaC** [comment]
Fixed!

ee66b5a7e89fa000eafb8542b81546d6140a3949
